language: node_js
node_js:
  - "7"
  - "6"
# before_install:
# install:
before_script:
  - "cp example/nodeCordovaTools.js ../nodeCordovaTools.js"
  - "cd .. "
  - "npm install -g cordova"
script:
  - "node node-cordova-tools/src/cordova-create.js"
