# http://lint.travis-ci.org/

language: node_js
node_js:
  - "7"
  - "6"
before_install:
  - "cp -r example/* ../"
  - "cd .."
install:
  - "npm install -g cordova"
  - "npm install"
# before_script:
script:
  - "ls"
  - "node node-cordova-tools/src/projectPath-delete.js"
  - "node node-cordova-tools/src/cordova-create.js"
  - "node node-cordova-tools/src/cordova-platforms-add.js"
  - "node node-cordova-tools/src/cordova-plugins-add.js"
  - "node node-cordova-tools/src/cordova-clean-images.js"
  - "node node-cordova-tools/src/xml-version.js"
  - "node node-cordova-tools/src/copy.js"
